#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config focused_border_color \#e5e9f0
bspc config window_gap          10
bspc config click_to_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Steam desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a dota2 desktop=^10

# Setup wallpaper etc
export DESKTOP_SESSION=gnome
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

feh --bg-fill ~/.wallpaper &
xsetroot -cursor_name left_ptr &
polybar example &
~/git/qmlnotify/bin/qmlnotify --qml ~/Notification.qml &
compton --config ~/.config/compton.conf &

# Autostart script
sh ~/.autostart

